### ISSUE TITLE
caught them all, still no pass

### ISSUE THREAD

**Issue by tomheffels** [Codaisseur/dataTransFormationExercises#4]
Hello Rein,

In part 3 (data mining) the getTrainerPokemons test does not allow you to get the pokemon in another order than specified in the test.

Here's my code, I logged the Trainer IDs and the Array of Pokemon to check if they're all there.

const getTrainerPokemons = (trainer, pokemons) => {
        console.log(trainer.pokemonIds)
        console.log(pokemons.filter(pokemon => trainer.pokemonIds.includes(pokemon.id)))
        return pokemons.filter(pokemon => trainer.pokemonIds.includes(pokemon.id))
} 

Cheers,

Tom

**Comment by tomheffels** [comment]
fixed it! 

expect(teamAsh).toEqual(expect.any(Array))
expect(teamAsh.map(pokemon => pokemon.name)).toEqual(expect.arrayContaining([
        'Pikachu', "Bulbasaur", "Squirtle", "Charizard", "Pidgeotto", "Butterfree"
    ]))
expect(teamAsh.length === 6)

**Comment by Reinoptland** [comment]
Thanks Tom! Solved in #6
